const expenses = [
  {
    id: 1,
    employeeName: 'Vaibhav Randale',
    employee_id: '19072023009',
    email: 'vaibhav.randale@taypro.in',
    sitename: 'Avaada  Avaada Client Visit',
    siteLocation: 'Delhi',
    startDate: '12/02/2024',
    endDate: '15/02/2024',
    status: 1,
    ApprovedBy: 'Tejas Memane',
    ApprovedBy2: '',
    ApprovedAt: '30/03/2024',
    AdvanceAmount: '3000',
    AdvanceAmountDate: '11/02/2024',

    Settled: 0,
    SettledBy: '',
    daywiseExpensens: [
      {
        id: 1,
        date: '12/02/2024',
        expense: 'Breakfast',
        price: '200',
        img: '/images/bills/bill1.png',
      },
      {
        id: 2,
        date: '12/02/2024',
        expense: 'Lunch',
        price: '250',
        img: '/images/bills/bill2.png',
      },
      {
        id: 3,
        date: '12/02/2024',
        expense: 'Travel',
        price: '300',
        img: '/images/bills/bill3.png',
      },
      {
        id: 4,
        date: '13/02/2024',
        expense: 'Breakfast',
        price: '250',
        img: '/images/bills/bill3.png',
      },

      {
        id: 5,
        date: '14/02/2024',
        expense: 'Day 3 Expense',
        price: '2250',
        img: '/images/bills/bill3.png',
      },
    ],
  },

  {
    id: 2,
    employeeName: 'Yogesh Kudale',
    employee_id: '123456789',
    email: 'yogesh@taypro.in',
    sitename: 'Tata Chhayan site Visit',
    siteLocation: 'Pokhran- Noorsar',
    startDate: '18/02/2024',
    endDate: '22/02/2024',
    status: 1,
    ApprovedBy: 'Tejas Memane',
    ApprovedBy2: '',
    ApprovedAt: '30/03/2024',
    Settled: 0,
    SettledBy: '',

    AdvanceAmount: '2000',
    AdvanceAmountDate: '17/02/2024',
    daywiseExpensens: [
      {
        id: 1,
        date: '18/02/2024',
        expense: 'Travel',
        price: '200',
        img: '/images/bills/bill1.png',
      },
      {
        id: 2,
        date: '18/02/2024',
        expense: 'Breakfast',
        price: '150',
        img: '/images/bills/bill2.png',
      },
      {
        id: 3,
        date: '18/02/2024',
        expense: 'Lunch',
        price: '200',
        img: '/images/bills/bill3.png',
      },
    ],
  },
  {
    id: 3,
    employeeName: 'Alice Johnson',
    employee_id: '111111111',
    email: 'alice.johnson@example.com',
    sitename: 'Business Trip',
    siteLocation: 'Chicago',
    startDate: '10/03/2024',
    endDate: '12/03/2024',
    status: 2,
    ApprovedBy: 'Bob Anderson',
    ApprovedBy2: 'Eva Williams',
    ApprovedAt: '20/03/2024',
    AdvanceAmount: '3000',
    AdvanceAmountDate: '05/03/2024',
    Settled: 0,
    SettledBy: '',
    daywiseExpensens: [
      {
        id: 1,
        date: '10/03/2024',
        expense: 'Flight',
        price: '500',
        img: '/images/bills/bill1.png',
      },
      {
        id: 2,
        date: '11/03/2024',
        expense: 'Accommodation',
        price: '300',
        img: '/images/bills/bill2.png',
      },
      {
        id: 3,
        date: '12/03/2024',
        expense: 'Dinner',
        price: '200',
        img: '/images/bills/bill3.png',
      },
    ],
  },
  {
    id: 4,
    employeeName: 'Bob Anderson',
    employee_id: '222222222',
    email: 'bob.anderson@example.com',
    sitename: 'Client Meeting',
    siteLocation: 'New York',
    startDate: '15/03/2024',
    endDate: '18/03/2024',
    status: 1,
    ApprovedBy: 'Eva Williams',
    ApprovedBy2: '',
    ApprovedAt: '25/03/2024',
    AdvanceAmount: '2500',
    AdvanceAmountDate: '12/03/2024',
    Settled: 1,
    SettledBy: 'Alice Johnson',
    daywiseExpensens: [
      {
        id: 1,
        date: '15/03/2024',
        expense: 'Taxi',
        price: '50',
        img: '/images/bills/bill4.png',
      },
      {
        id: 2,
        date: '16/03/2024',
        expense: 'Dinner',
        price: '120',
        img: '/images/bills/bill5.png',
      },
      {
        id: 3,
        date: '17/03/2024',
        expense: 'Accommodation',
        price: '250',
        img: '/images/bills/bill6.png',
      },
    ],
  },
];

export default expenses;
