import bcrypt from 'bcryptjs';

const data = {
  employees: [
    {
      employee_id: '19007223009',
      name: 'Vaibhav Randale',
      image: '/images/Vaibhav_Randale.jpg',
      email: 'vaibhav.randale@taypro.in',
      password: '19007223009',
      isAdmin: true,

      isSuperAdmin: true,
      isSales: true,
      isScm: true,
      isDesign: true,
      isProject: true,
      isVisitor: false,
      isProduction: true,
      isAccountant: true,
      joiningDate: '1/03/2023',
      birth_date: '24/06/1999',
      gender: 'male',
      designation: 'abc',
      state: 'maharashtra',
      address: 'abc,xyz,pqr',
      mobile_no: '1234567890',
      age: '22',
      experience: '1',
      activate: true,
      aadhar_no: '1122334408',

      leaves: 10,

      pf_account_no: '11223344',
      bank_account_no: '1122334455',
      uan_number: '390324',
      pan_number: 'werrt123',

      payslips: [
        {
          status: true,
          month: 'July',
          year: 2023,
          salary: 25000,
          deductions: 200,
          deductionReason: 'NA',
          bonuses: 0,
        },
        {
          status: true,
          month: 'June',
          year: 2023,
          salary: 22000,
          deductions: 200,
          deductionReason: 'NA',
          bonuses: 0,
        },
        {
          status: true,
          month: 'May',
          year: 2023,
          salary: 21000,
          deductions: 200,
          deductionReason: 'NA',
          bonuses: 0,
        },
      ],
    },
    // {
    //   employee_id: '20192020',
    //   name: 'Chaitanya Andure',
    //   image: '/images/Chaitanya_Andure.png',
    //   email: 'chaitanya.andure@taypro.in',
    //   password: '20192020',
    //   isAdmin: true,
    //   isSuperAdmin: false,
    //   isSales: false,
    //   isScm: true,
    //   isDesign: false,
    //   isProject: false,
    //   isVisitor: false,
    //   isProduction: false,
    //   isAccountant: false,
    //   joiningDate: '1/03/2023',
    //   birth_date: '24/06/2000',
    //   gender: 'male',
    //   designation: 'abc',
    //   state: 'maharashtra',
    //   address: 'abc,xyz,pqr',
    //   mobile_no: '1234567890',
    //   age: '22',
    //   experience: '1',
    //   activate: false,

    //   leaves: 10,

    //   pf_account_no: '11223341',
    //   bank_account_no: '11223344552',
    //   uan_number: '390324e4',
    //   pan_number: 'werrt12333',

    //   payslips: [
    //     {
    //       status: true,
    //       month: 'June',
    //       year: 2023,
    //       salary: 25000,
    //       deductions: 200,
    //       deductionReason: 'NA',
    //       bonuses: 0,
    //     },
    //   ],
    // },
    {
      employee_id: '20192021',
      name: 'Satyajeet Patil',
      image: '/images/Satyajit_patil.png',
      email: 'satyajeet.patil@taypro.in',
      password: '20192021',
      isAdmin: true,
      isSuperAdmin: false,
      isSales: false,
      isScm: false,
      isDesign: true,
      isProject: false,
      isVisitor: false,
      isProduction: false,
      isAccountant: false,
      joiningDate: '1/03/2023',
      birth_date: '24/06/2000',
      gender: 'male',
      designation: 'abc',
      state: 'maharashtra',
      address: 'abc,xyz,pqr',
      mobile_no: '1234567890',
      age: '22',
      experience: '1',
      activate: true,
      aadhar_no: '112233409',

      leaves: 10,

      pf_account_no: '1122334423',
      bank_account_no: '112233445532',
      uan_number: '39032444',
      pan_number: 'werrt12322',

      payslips: [
        {
          status: true,
          month: 'April',
          year: 2023,
          salary: 26000,
          deductions: 200,
          deductionReason: 'NA',
          bonuses: 0,
        },
      ],
    },
    {
      employee_id: '20192022',
      name: 'Tejas Memane',
      image: '/images/icons/employee.png',
      email: 'tejas.memane@taypro.in',
      password: '20192022',
      isAdmin: true,
      isSuperAdmin: true,
      isSales: true,
      isScm: true,
      isDesign: true,
      isProject: true,
      isVisitor: false,
      isProduction: true,
      isAccountant: true,
      joiningDate: '1/03/2018',
      birth_date: '24/06/1993',
      gender: 'male',
      designation: 'abc',
      state: 'maharashtra',
      address: 'abc,xyz,pqr',
      mobile_no: '1234567890',
      age: '27',
      experience: '5',
      activate: true,
      aadhar_no: '112233410',

      leaves: 10,

      pf_account_no: '1122334434',
      bank_account_no: '112233445e5',
      uan_number: '3903254454',
      pan_number: 'werrt123232',

      payslips: [
        {
          status: true,
          month: 'June',
          year: 2023,
          salary: 125000,
          deductions: 200,
          deductionReason: 'NA',
          bonuses: 0,
        },
      ],
    },

    {
      employee_id: '20192023',
      name: 'Abhay Singh',
      image: '/images/Abhay_Singh.png',
      email: 'abhay.singh@taypro.in',
      password: '20192023',
      isAdmin: true,
      isSuperAdmin: false,
      isSales: false,
      isScm: false,
      isDesign: false,
      isProject: true,
      isVisitor: false,
      isProduction: false,
      isAccountant: false,
      joiningDate: '1/03/2023',
      birth_date: '24/06/2000',
      gender: 'male',
      designation: 'abc',
      state: 'UP',
      address: 'abc,xyz,pqr',
      mobile_no: '1234567890',
      age: '22',
      experience: '1',
      activate: true,
      aadhar_no: '11223341',

      leaves: 10,

      pf_account_no: '1122113344',
      bank_account_no: '112211334455',
      uan_number: '39011324',
      pan_number: 'werrt11123',

      payslips: [
        {
          status: true,
          month: 'May',
          year: 2023,
          salary: 35000,
          deductions: 200,
          deductionReason: 'NA',
          bonuses: 0,
        },
      ],
    },
    {
      employee_id: '20192024',
      name: 'Vaibhav Gujar',
      image: '/images/icons/employee.png',
      email: 'vaibhav.g@taypro.in',
      password: '20192024',
      isAdmin: true,
      isSuperAdmin: false,
      isSales: false,
      isScm: false,
      isDesign: false,
      isProject: true,
      isVisitor: false,
      isProduction: false,
      isAccountant: false,
      joiningDate: '1/03/2023',
      birth_date: '24/06/2000',
      gender: 'male',
      designation: 'abc',
      state: 'UP',
      address: 'abc,xyz,pqr',
      mobile_no: '1234567890',
      age: '22',
      experience: '1',
      activate: true,
      aadhar_no: '11223342',

      leaves: 10,

      pf_account_no: '1122223344',
      bank_account_no: '112222334455',
      uan_number: '39022324',
      pan_number: 'werrt22123',

      payslips: [
        {
          status: true,
          month: 'March',
          year: 2023,
          salary: 25000,
          deductions: 200,
          deductionReason: 'NA',
          bonuses: 0,
        },
      ],
    },
    {
      employee_id: '20192017',
      name: 'Yogesh Kudale',
      image: '/images/icons/employee.png',
      email: 'yogesh@taypro.in',
      password: '20192017',
      isAdmin: true,
      isSuperAdmin: true,
      isSales: true,
      isScm: true,
      isDesign: true,
      isProject: true,
      isVisitor: false,
      isProduction: true,
      isAccountant: true,
      joiningDate: '1/03/2023',
      birth_date: '24/06/2000',
      gender: 'male',
      designation: 'abc',
      state: 'UP',
      address: 'abc,xyz,pqr',
      mobile_no: '1234567890',
      age: '22',
      experience: '1',
      activate: true,
      aadhar_no: '11223343',

      leaves: 10,

      pf_account_no: '1122311344',
      bank_account_no: '111122334455',
      uan_number: '3903214',
      pan_number: 'wer1rt1123',

      payslips: [
        {
          status: true,
          month: 'Feb',
          year: 2023,
          salary: 25000,
          deductions: 200,
          deductionReason: 'NA',
          bonuses: 0,
        },
      ],
    },
    {
      employee_id: 'external2019',
      name: 'External',
      image: '/images/icons/employee.png',
      email: 'external@taypro.in',
      password: 'external2019',
      isAdmin: true,
      isSuperAdmin: false,
      isSales: false,
      isScm: false,
      isDesign: false,
      isProject: false,
      isVisitor: true,
      isProduction: false,
      isAccountant: false,
      joiningDate: '1/03/2023',
      birth_date: '24/06/2000',
      gender: 'male',
      designation: 'abc',
      state: 'UP',
      address: 'abc,xyz,pqr',
      mobile_no: '1234567890',
      age: '22',
      experience: '1',
      activate: true,
      aadhar_no: '11223344',

      leaves: 10,

      pf_account_no: '1111223344',
      bank_account_no: '111122334455',
      uan_number: '3q190324',
      pan_number: 'werr12t123',

      payslips: [
        {
          status: true,
          month: 'June',
          year: 2023,
          salary: 25000,
          deductions: 200,
          deductionReason: 'NA',
          bonuses: 0,
        },
      ],
    },
    {
      employee_id: '20192026',
      name: 'Nitish Kshirsagar',
      image: '/images/icons/employee.png',
      email: 'nitish.k@taypro.in',
      password: '20192026',
      isAdmin: true,
      isSuperAdmin: false,
      isSales: true,
      isScm: false,
      isDesign: false,
      isProject: false,
      isVisitor: false,
      isProduction: false,
      isAccountant: false,
      joiningDate: '1/03/2023',
      birth_date: '24/06/2000',
      gender: 'male',
      designation: 'abc',
      state: 'MH',
      address: 'abc,xyz,pqr',
      mobile_no: '1234567890',
      age: '22',
      experience: '1',
      activate: true,
      aadhar_no: '11223345',

      leaves: 10,

      pf_account_no: '121223344',
      bank_account_no: '166122334455',
      uan_number: '39660324',
      pan_number: 'we66rrt123',

      payslips: [
        {
          status: true,
          month: 'August',
          year: 2023,
          salary: 25000,
          deductions: 200,
          deductionReason: 'NA',
          bonuses: 0,
        },
      ],
    },

    {
      employee_id: '20192027',
      name: 'Abhishek Mansurkar',
      image: '/images/icons/employee.png',
      email: 'abhishek@taypro.in',
      password: '20192027',
      isAdmin: true,
      isSuperAdmin: true,
      isSales: true,
      isScm: true,
      isDesign: true,
      isProject: true,
      isVisitor: false,
      isProduction: true,
      isAccountant: true,
      joiningDate: '1/03/2023',
      birth_date: '24/06/2000',
      gender: 'male',
      designation: 'abc',
      state: 'MH',
      address: 'abc,xyz,pqr',
      mobile_no: '1234567890',
      age: '22',
      experience: '1',
      activate: true,
      aadhar_no: '11223347',

      leaves: 10,

      pf_account_no: '1121123344',
      bank_account_no: '111122334455',
      uan_number: '39110324',
      pan_number: 'we11rrt123',

      payslips: [
        {
          status: true,
          month: 'June',
          year: 2023,
          salary: 25000,
          deductions: 200,
          deductionReason: 'NA',
          bonuses: 0,
        },
      ],
    },
    {
      employee_id: '20192028',
      name: 'Akshay Auti',
      image: '/images/icons/employee.png',
      email: 'akshay@taypro.in',
      password: '20192028',
      isAdmin: true,
      isSuperAdmin: true,
      isSales: true,
      isScm: true,
      isDesign: true,
      isProject: true,
      isVisitor: false,
      isProduction: true,
      isAccountant: true,
      joiningDate: '1/03/2023',
      birth_date: '24/06/2000',
      gender: 'male',
      designation: 'abc',
      state: 'MH',
      address: 'abc,xyz,pqr',
      mobile_no: '1234567890',
      age: '22',
      experience: '1',
      activate: true,
      aadhar_no: '11223349',

      leaves: 10,

      pf_account_no: '111199223344',
      bank_account_no: '99111122334455',
      uan_number: '39099324',
      pan_number: 'w88errt123',

      payslips: [
        {
          status: true,
          month: 'April',
          year: 2023,
          salary: 25000,
          deductions: 200,
          deductionReason: 'NA',
          bonuses: 0,
        },
      ],
    },

    {
      employee_id: '20192029',
      name: 'Pooja Deshmane',
      image: '/images/Pooja_Deshmane.png',
      email: 'pooja.deshmane@taypro.in',
      password: '20192029',
      isAdmin: true,
      isSuperAdmin: true,
      isSales: false,
      isScm: false,
      isDesign: false,
      isProject: false,
      isVisitor: false,
      isProduction: false,
      isAccountant: true,
      joiningDate: '1/03/2023',
      birth_date: '24/06/2000',
      gender: 'male',
      designation: 'abc',
      state: 'MH',
      address: 'abc,xyz,pqr',
      mobile_no: '1234567890',
      age: '22',
      experience: '1',
      activate: true,
      aadhar_no: '11223340',

      leaves: 10,

      pf_account_no: '1661223344',
      bank_account_no: '661122334455',
      uan_number: '39036624',
      pan_number: 'werrt16623',

      payslips: [
        {
          status: true,
          month: 'July',
          year: 2023,
          salary: 25000,
          deductions: 200,
          deductionReason: 'NA',
          bonuses: 0,
        },
      ],
    },
  ],
  Leaves: [
    {
      leaveId: 1,
      employee_id: '20192019',
      name: 'Vaibhav Randale',
      type: 'sick',
      other: '',
      noOfLeaves: '3',
      expectedDateOfLeave: '22/06/2023',
      expectedDateOfreturn: '30/06/2023',
      submittedAt: '22/06/2022',
      reasonInDetail:
        'The urgency or emotional effects of a personal situation often' +
        ' affect how people act because they manage stress differently. Make sure that,' +
        ' despite the situation, you politely request leave from work rather than demand it',
      mobileNo: '8007923255',
      approved: true,
      approvedBy: 'Yogesh Kudale',
      remark: 'You can take leave at this moment',
      remarkBy: 'Yogesh kudale',
      approvedAt: '23/06/2022',
    },
    {
      leaveId: 2,
      employee_id: '20192020',
      name: 'chaitaynya andure',
      type: 'sick',
      other: '',
      noOfLeaves: '3',
      expectedDateOfLeave: '1/06/2023',
      expectedDateOfreturn: '2/06/2023',
      submittedAt: '22/06/2022',
      reasonInDetail:
        'The urgency or emotional effects of a personal situation often' +
        ' affect how people act because they manage stress differently. Make sure that,' +
        ' despite the situation, you politely request leave from work rather than demand it',
      mobileNo: '8007923255',
      approved: true,
      approvedBy: 'Yogesh Kudale',
      remark: 'You Can take',
      remarkBy: 'Yogesh kudale',
      approvedAt: '23/06/2022',
    },
    {
      leaveId: 3,
      employee_id: '20192019',
      name: 'Vaibhav Randale',
      type: 'sick',
      other: '',
      noOfLeaves: '3',
      expectedDateOfLeave: '8/06/2023',
      expectedDateOfreturn: '11/06/2023',
      submittedAt: '22/06/2022',
      reasonInDetail:
        'The urgency or emotional effects of a personal situation often' +
        ' affect how people act because they manage stress differently. Make sure that,' +
        ' despite the situation, you politely request leave from work rather than demand it',
      mobileNo: '8007923255',
      approved: false,
      approvedBy: '',
      remark: 'You Could not take leave at this moment',
      remarkBy: 'Yogesh kudale',
      approvedAt: '',
    },
    {
      leaveId: 4,
      employee_id: '20192019',
      name: 'Vaibhav Randale',
      type: 'sick',
      other: '',
      noOfLeaves: '3',
      expectedDateOfLeave: '8/06/2023',
      expectedDateOfreturn: '11/06/2023',
      submittedAt: '22/06/2022',
      reasonInDetail:
        'The urgency or emotional effects of a personal situation often' +
        ' affect how people act because they manage stress differently. Make sure that,' +
        ' despite the situation, you politely request leave from work rather than demand it',
      mobileNo: '8007923255',
      approved: false,
      approvedBy: '',
      remark: 'You Could not take leave at this moment',
      remarkBy: 'Yogesh kudale',
      approvedAt: '',
    },
    {
      leaveId: 5,
      employee_id: '20192020',
      name: 'chaitaynya andure',
      type: 'sick',
      other: '',
      noOfLeaves: '3',
      expectedDateOfLeave: '8/06/2023',
      expectedDateOfreturn: '11/06/2023',
      submittedAt: '22/06/2022',
      reasonInDetail:
        'The urgency or emotional effects of a personal situation often' +
        ' affect how people act because they manage stress differently. Make sure that,' +
        ' despite the situation, you politely request leave from work rather than demand it',
      mobileNo: '8007923255',
      approved: true,
      approvedBy: 'Yogesh Kudale',
      remark: 'You can take leave at this moment',
      approvedAt: '23/06/2022',
      remarkBy: 'Yogesh kudale',
    },
  ],

  siteDetails: [
    {
      projectCode: '112233',
      customerName: 'Avaada',
      customerLogo: '/images/avaada_logo.png',
      siteLocation: 'Karnataka',
      plantCapacity: '200MW',
      plantLayout: '/plantA.pdf',
    },
    {
      projectCode: '112234',
      customerName: 'Ayana',
      customerLogo: '/images/ayana_logo.png',
      siteLocation: 'Karnataka',
      plantCapacity: '200MW',
      plantLayout: '/plantA.pdf',
    },
  ],

  SiteSurvey: [
    {
      surveyId: '1',
      projectCode: '112233',
      block: 'Block 1',
      table: 'table 1',
      structure: '2P',
      row: 'row 1',
      A: '1',
      ImageA: '',
      B: '1',
      ImageB: '',
      C: '11',
      ImageC: '/images/taypro_standard_c.png',
      D: '1',
      ImageD: '',
      E: '1',
      ImageE: '',
      F: '1',
      ImageF: '',
      G: '12',
      ImageG: '/images/taypro_standard_g.png',
      H: '1',
      ImageH: '',
      I: '1',
      ImageI: '',
      J: '1',
      ImageJ: '',
      htablex: '1',
      htabley: '3',
      img: '/images/taypro_standard.png',
      submittedBy: 'Vaibhav Randale',
      submittedByEmail: 'vaibhav.randale@taypro.in',
      submittedAt: '12/12/2023',
      rating: 0,
      numReviews: 0,
      status: false,
    },
    {
      surveyId: '2',
      projectCode: '112234',
      block: 'Block 2',
      table: 'table 1',
      row: 'row 2',
      structure: '2P',
      A: '12',
      ImageA: '',
      B: '12',
      ImageB: '',
      C: '11',
      ImageC: '/images/taypro_standard_c.png',
      D: '12',
      ImageD: '',
      E: '12',
      ImageE: '',
      F: '12',
      ImageF: '',
      G: '12',
      ImageG: '/images/taypro_standard_g.png',
      H: '12',
      ImageH: '',
      I: '12',
      ImageI: '',
      J: '12',
      ImageJ: '',
      img: '/images/taypro_standard.png',
      submittedBy: 'Vaibhav Randale',
      submittedByEmail: 'vaibhav.randale@taypro.in',
      submittedAt: '12/12/2023',
      htablex: '',
      htabley: '',
      status: false,
      rating: 0,
      numReviews: 0,
    },
  ],
};

export default data;
