import bcrypt from 'bcryptjs';

const data = {
  // employees: [],
  employees: [
    // {
    //   employee_id: '201908',
    //   UID: '5014F559',
    //   firstName: 'Vaibhav',
    //   lastName: 'Randale',
    //   NAME: 'Vaibhav Randale',
    //   image:
    //     'https://res.cloudinary.com/di0iwc8ql/image/upload/v1709110939/eu8voe7x1vtpnesmlhhs.jpg',
    //   email: 'vaibhav.randale@taypro.in',
    //   password: bcrypt.hashSync('201908'),
    //   isAdmin: 1,
    //   isSuperAdmin: 1,
    //   isSales: 0,
    //   isScm: 0,
    //   isDesign: 0,
    //   isProject: 0,
    //   isVisitor: 0,
    //   isProduction: 0,
    //   isAccountant: 0,
    //   isHr: 0,
    //   isDirector: 0,
    //   isSoftwareDevlopment: 1,
    //   isHardwareDevlopment: 0,
    //   joiningDate: '01/03/2023',
    //   birth_date: '24/06/2000',
    //   gender: 'male',
    //   designation: 'Web Developer',
    //   state: 'Maharashtra',
    //   address: 'Plot no 9,Sector 16, Taloja Phase 2, Navi Mumbai ',
    //   addressProof: '/path/to/dummy/file.jpg',
    //   mobile_no: '8007923255',
    //   age: '24',
    //   experience: '0',
    //   activate: 1,
    //   leaves: 18,
    //   sick: 3,
    //   privilege: 12,
    //   casual: 3,
    //   aadhar_no: '776749750261',
    //   pf_account_no: '',
    //   bank_account_no: '',
    //   ifsc_code: '',
    //   pan_number: 'EIQPR0122A',
    //   father_husband_name: 'Rachappa Randale',
    //   marital_status: 'single',
    //   sub_locality: 'Taloja Metro Station',
    //   district: 'Raigarh',
    //   pinCode: '410206',
    //   nominee_name: 'Rachappa Randale',
    //   nominee_relationship: 'Father',
    //   nominee_address: '1',
    //   nominee_sub_locality: 'Plot no 9,Sector 16, Taloja Phase 2, Navi Mumbai',
    //   nominee_district: 'Raigarh',
    //   nominee_state: 'Maharashtra',
    //   nominee_mobile_no: '9552144231',
    //   nominee_pinCode: '410206',
    //   nominee_email: 'randale72@gmail.com',
    //   no_of_family_members: '4',
    //   alternate_mobile_no: '9551144231',
    //   personal_email: 'vaibhavrandale800@gmail.com',
    //   aadhar_card_file: '/path/to/dummy/file.jpg',
    //   pan_card_file: '/path/to/dummy/file.jpg',
    //   bank_account_file: '/path/to/dummy/file.jpg',
    //   experience_letter: 'fresher',
    //   tenth_marksheet: '/path/to/dummy/file.jpg',
    //   tenth_schoolName: 'Shree Mahadev Vidhyalay Dhanegaon',
    //   tenth_grade: '90.60',
    //   twelth_or_diploma_marksheet: '/path/to/dummy/file.jpg',
    //   twelth_or_diploma_collegeName: 'Purnmal Lahoti Government Latur',
    //   twelth_or_diploma_grade: '88.06',
    //   under_geaduate_or_post_graduate_marksheet: '/path/to/dummy/file.jpg',
    //   under_geaduate_or_post_graduate_collegeName:
    //     'Pimpri Chinchwad College of Engineering , Pune',
    //   under_geaduate_or_post_graduate_grade: '8.36',
    //   previous_company_name: 'fresher',
    //   isProbation: 1,
    // },
  ],

  // Payslip: [],
  Payslip: [
    // {
    //   employee_id: '19072023009',
    //   firstName: 'Vaibhav',
    //   lastName: 'Randale',
    //   NAME: 'Vaibhav Randale',
    //   email: 'vaibhav.randale@taypro.in',
    //   ctc: 400000,
    //   basic: 11250,
    //   salarygroup: 5,
    //   hra: 4500,
    //   conveyance: 1600,
    //   medical: 1250,
    //   special: 6400,
    //   pt: 200,
    //   pf: 1350,
    //   esi: 0,
    //   total_deduction: 1550,
    //   gross: 25000,
    //   netsalary: 23450,
    //   employer_pf: 1462.5,
    //   employer_esi: 0,
    //   bonus: 937.12,
    //   month: 3,
    //   year: 2024,
    // },
  ],

  holidays: [
    // {
    //   name: "New Year's Day",
    //   img: '/images/happynewyear.avif',
    //   date: '01/01/2024',
    //   description: 'Celebration of the beginning of the new year.',
    // },
    // {
    //   name: 'Independence Day',
    //   img: '/images/independance.avif',
    //   date: '04/07/2024',
    //   description: 'Celebration of national independence.',
    // },
  ],

  RfidReg: [
    // {
    //   UID: '5014F559',
    //   NAME: 'Vaibhav Randale',
    //   Reg_no: '19072023009',
    //   email: 'vaibhav.randale@taypro.in',
    //   Contact_No: '1234567890',
    // },
  ],
  RfidCkeck: [],
  birthdayWish: [],
  AttendanceRecord: [],

  siteDetails: [
    // {
    //   projectCode: '112233',
    //   customerName: 'Avaada',
    //   customerLogo: '/images/avaada_logo.png',
    //   siteLocation: 'Karnataka',
    //   plantCapacity: '200MW',
    //   plantLayout: '/plantA.pdf',
    // },
    // {
    //   projectCode: '112234',
    //   customerName: 'Ayana',
    //   customerLogo: '/images/ayana_logo.png',
    //   siteLocation: 'Karnataka',
    //   plantCapacity: '200MW',
    //   plantLayout: '/plantA.pdf',
    // },
  ],
  EmployeeExpense: [
    // {
    //   // id: 1,
    //   employeeName: 'Vaibhav Randale',
    //   employee_id: '19072023009',
    //   email: 'vaibhav.randale@taypro.in',
    //   sitename: 'Avaada  Avaada Client Visit',
    //   siteLocation: 'Delhi',
    //   startDate: '12/02/2024',
    //   endDate: '15/02/2024',
    //   status: 1,
    //   ApprovedBy: 'Tejas Memane',
    //   ApprovedBy2: '',
    //   ApprovedAt: '30/03/2024',
    //   AdvanceAmount: '3000',
    //   AdvanceAmountDate: '11/02/2024',
    //   Settled: 0,
    //   SettledBy: '',
    // },
  ],
  DaywiseExpenses: [
    // {
    //   // id: 1,
    //   date: '12/02/2024',
    //   expense: 'Breakfast',
    //   price: '200',
    //   img: '/images/bills/bill1.png',
    // },
    // {
    //   // id: 2,
    //   date: '12/02/2024',
    //   expense: 'Lunch',
    //   price: '250',
    //   img: '/images/bills/bill2.png',
    // },
    // {
    //   // id: 3,
    //   date: '12/02/2024',
    //   expense: 'Travel',
    //   price: '300',
    //   img: '/images/bills/bill3.png',
    // },
    // {
    //   // id: 4,
    //   date: '13/02/2024',
    //   expense: 'Breakfast',
    //   price: '250',
    //   img: '/images/bills/bill3.png',
    // },
    // {
    //   // id: 5,
    //   date: '14/02/2024',
    //   expense: 'Day 3 Expense',
    //   price: '2250',
    //   img: '/images/bills/bill3.png',
    // },
  ],
  EmployeeAssets: [],
  Policy: [],
  notices: [],
  Leaves: [],
  Anniversary: [],
  attendanceData: [],
  AttendanceRecord: [],
  SiteSurvey: [
    // {
    //   projectCode: 'your_project_code',
    //   block: 'Block A',
    //   surveyId: 'taypro1628528548421',
    //   row: 'Row 1',
    //   table: 4,
    //   structure: 'Struct1',
    //   A: 'Value A',
    //   ImageA: 'image_a.jpg',
    //   B: 'Value B',
    //   ImageB: 'image_b.jpg',
    //   C: 'Value C',
    //   ImageC: 'image_c.jpg',
    //   D: 'Value D',
    //   ImageD: 'image_d.jpg',
    //   E: 'Value E',
    //   ImageE: 'image_e.jpg',
    //   F: 'Value F',
    //   ImageF: 'image_f.jpg',
    //   G: 'Value G',
    //   ImageG: 'image_g.jpg',
    //   H: ['H1', 'H2', 'H3'], // Array with 3 values
    //   ImageH: [
    //     '/images/taypro_standard_a.png',
    //     '/images/taypro_standard_c.png',
    //     '/images/taypro_standard_c.png',
    //   ], // Array with 3 values
    //   htablex: ['x1', 'x2', 'x3'], // Array with 3 values
    //   htabley: ['y1', 'y2', 'y3'], // Array with 3 values
    //   I: 'Value I',
    //   ImageI: 'image_i.jpg',
    //   J: 'Value J',
    //   ImageJ: 'image_j.jpg',
    //   submittedBy: 'John Doe',
    //   submittedByEmail: 'john@example.com',
    //   submittedAt: '2023-08-09T12:34:56.789Z',
    //   rating: 0,
    //   numReviews: 0,
    //   verifiedBy: '',
    //   verifiededAt: '',
    //   img: '',
    // },
  ],
};

export default data;
