const data = {
  employees: [
    {
      employee_id: '20192019',
      name: 'Vaibhav Randale',
      image: '/images/Vaibhav_Randale.jpg',
      email: 'vaibhav.randale@taypro.in',
      isAdmin: true,
      joiningDate: '1/03/2023',
      birth_date: '24/06/1999',
      gender: 'male',
      designation: 'abc',
      state: 'maharashtra',
      address: 'abc,xyz,pqr',
      mobile_no: '1234567890',
      age: '22',
      experience: '1',
      activate: true,

      leaves: 10,
    },
    {
      employee_id: '20192020',
      name: 'Chaitanya Andure',
      image: '/images/Chaitanya_Andure.png',
      email: 'chaitanya.andure@taypro.in',
      isAdmin: false,
      joiningDate: '1/03/2023',
      birth_date: '24/06/2000',
      gender: 'male',
      designation: 'abc',
      state: 'maharashtra',
      address: 'abc,xyz,pqr',
      mobile_no: '1234567890',
      age: '22',
      experience: '1',
      activate: false,

      leaves: 10,
    },
    {
      employee_id: '20192021',
      name: 'Satyajeet Patil',
      image: '/images/Satyajit_patil.png',
      email: 'satyajeet.patil@taypro.in',
      isAdmin: true,
      joiningDate: '1/03/2023',
      birth_date: '24/06/2000',
      gender: 'male',
      designation: 'abc',
      state: 'maharashtra',
      address: 'abc,xyz,pqr',
      mobile_no: '1234567890',
      age: '22',
      experience: '1',
      activate: true,

      leaves: 10,
    },
    {
      employee_id: '20192022',
      name: 'Tejas Memane',
      image: '/images/icons/employee.png',
      email: 'tejas.memane@taypro.in',
      isAdmin: true,
      joiningDate: '1/03/2018',
      birth_date: '24/06/1993',
      gender: 'male',
      designation: 'abc',
      state: 'maharashtra',
      address: 'abc,xyz,pqr',
      mobile_no: '1234567890',
      age: '27',
      experience: '5',
      activate: true,

      leaves: 10,
    },
    {
      employee_id: '20192023',
      name: 'Abhay Singh',
      image: '/images/Abhay_Singh.png',
      email: 'abhay.singh@taypro.in',
      isAdmin: false,
      joiningDate: '1/03/2023',
      birth_date: '24/06/2000',
      gender: 'male',
      designation: 'abc',
      state: 'UP',
      address: 'abc,xyz,pqr',
      mobile_no: '1234567890',
      age: '22',
      experience: '1',
      activate: true,

      leaves: 10,
    },
  ],
  Leaves: [
    {
      leaveId: 1,
      employee_id: '20192019',
      name: 'Vaibhav Randale',
      type: 'sick',
      other: '',
      noOfLeaves: '3',
      expectedDateOfLeave: '22/06/2023',
      expectedDateOfreturn: '30/06/2023',
      submittedAt: '22/06/2022',
      reasonInDetail:
        'The urgency or emotional effects of a personal situation often' +
        ' affect how people act because they manage stress differently. Make sure that,' +
        ' despite the situation, you politely request leave from work rather than demand it',
      mobileNo: '8007923255',
      approved: true,
      approvedBy: 'Yogesh Kudale',
      remark: 'You can take leave at this moment',
      remarkBy: 'Yogesh kudale',
      approvedAt: '23/06/2022',
    },
    {
      leaveId: 2,
      employee_id: '20192020',
      name: 'chaitaynya andure',
      type: 'sick',
      other: '',
      noOfLeaves: '3',
      expectedDateOfLeave: '1/06/2023',
      expectedDateOfreturn: '2/06/2023',
      submittedAt: '22/06/2022',
      reasonInDetail:
        'The urgency or emotional effects of a personal situation often' +
        ' affect how people act because they manage stress differently. Make sure that,' +
        ' despite the situation, you politely request leave from work rather than demand it',
      mobileNo: '8007923255',
      approved: true,
      approvedBy: 'Yogesh Kudale',
      remark: 'You Can take',
      remarkBy: 'Yogesh kudale',
      approvedAt: '23/06/2022',
    },
    {
      leaveId: 3,
      employee_id: '20192019',
      name: 'Vaibhav Randale',
      type: 'sick',
      other: '',
      noOfLeaves: '3',
      expectedDateOfLeave: '8/06/2023',
      expectedDateOfreturn: '11/06/2023',
      submittedAt: '22/06/2022',
      reasonInDetail:
        'The urgency or emotional effects of a personal situation often' +
        ' affect how people act because they manage stress differently. Make sure that,' +
        ' despite the situation, you politely request leave from work rather than demand it',
      mobileNo: '8007923255',
      approved: false,
      approvedBy: '',
      remark: 'You Could not take leave at this moment',
      remarkBy: 'Yogesh kudale',
      approvedAt: '',
    },
    {
      leaveId: 4,
      employee_id: '20192019',
      name: 'Vaibhav Randale',
      type: 'sick',
      other: '',
      noOfLeaves: '3',
      expectedDateOfLeave: '8/06/2023',
      expectedDateOfreturn: '11/06/2023',
      submittedAt: '22/06/2022',
      reasonInDetail:
        'The urgency or emotional effects of a personal situation often' +
        ' affect how people act because they manage stress differently. Make sure that,' +
        ' despite the situation, you politely request leave from work rather than demand it',
      mobileNo: '8007923255',
      approved: false,
      approvedBy: '',
      remark: 'You Could not take leave at this moment',
      remarkBy: 'Yogesh kudale',
      approvedAt: '',
    },
    {
      leaveId: 5,
      employee_id: '20192020',
      name: 'chaitaynya andure',
      type: 'sick',
      other: '',
      noOfLeaves: '3',
      expectedDateOfLeave: '8/06/2023',
      expectedDateOfreturn: '11/06/2023',
      submittedAt: '22/06/2022',
      reasonInDetail:
        'The urgency or emotional effects of a personal situation often' +
        ' affect how people act because they manage stress differently. Make sure that,' +
        ' despite the situation, you politely request leave from work rather than demand it',
      mobileNo: '8007923255',
      approved: true,
      approvedBy: 'Yogesh Kudale',
      remark: 'You can take leave at this moment',
      approvedAt: '23/06/2022',
      remarkBy: 'Yogesh kudale',
    },
  ],

  siteDetails: [
    {
      projectCode: '112233',
      customerName: 'Avaada',
      customerLogo: '/images/avaada_logo.png',
      siteLocation: 'Karnataka',
      plantCapacity: '200MW',
      plantLayout: 'plantA.pdf',
      _id: '64bbb188163e962f351ab57d',
    },
    {
      projectCode: '112234',
      customerName: 'Ayana',
      customerLogo: '/images/ayana_logo.png',
      siteLocation: 'Karnataka',
      plantCapacity: '200MW',
      plantLayout: 'plantA.pdf',
      _id: '64bbb188163e962f351ab57e',
    },
  ],

  SiteSurvey: [
    {
      surveyId: '1',
      projectCode: '112233',
      block: 'Block 1',
      table: 'table 1',
      structure: '2P',
      row: 'row 1',
      A: '1',
      ImageA: '',
      B: '1',
      ImageB: '',
      C: '11',
      ImageC: '/images/taypro_standard_c.png',
      D: '1',
      ImageD: '',
      E: '1',
      ImageE: '',
      F: '1',
      ImageF: '',
      G: '12',
      ImageG: '/images/taypro_standard_g.png',
      H: '1',
      ImageH: '',
      I: '1',
      ImageI: '',
      J: '1',
      ImageJ: '',
      htablex: '1',
      htabley: '3',
      img: '/images/taypro_standard.png',
      submittedBy: 'Abhay Singh',
      submittedAt: '12/12/2023',
      rating: 0,
      numReviews: 0,
      status: false,
    },
    {
      surveyId: '2',
      projectCode: '112234',
      block: 'Block 2',
      table: 'table 1',
      row: 'row 2',
      structure: '2P',
      A: '12',
      ImageA: '',
      B: '12',
      ImageB: '',
      C: '11',
      ImageC: '/images/taypro_standard_c.png',
      D: '12',
      ImageD: '',
      E: '12',
      ImageE: '',
      F: '12',
      ImageF: '',
      G: '12',
      ImageG: '/images/taypro_standard_g.png',
      H: '12',
      ImageH: '',
      I: '12',
      ImageI: '',
      J: '12',
      ImageJ: '',
      img: '/images/taypro_standard.png',
      submittedBy: 'Abhay Singh',
      submittedAt: '12/12/2023',
      htablex: '',
      htabley: '',
      status: false,
      rating: 0,
      numReviews: 0,
    },
  ],
};

export default data;
