const holidays = [
  {
    id: 1,
    name: "New Year's Day",
    img: '/images/happynewyear.avif',
    date: '01/01/2024',
    description: 'Celebration of the beginning of the new year.',

    // style={{ color: '#f086f7' }}
  },
  {
    id: 2,
    name: 'Independence Day',
    img: '/images/independance.avif',
    date: '04/07/2024',
    description: 'Celebration of national independence.',
  },
  {
    id: 3,
    name: 'Labor Day',
    img: '/images/labourDay.png',
    date: '01/05/2024',
    description: 'Honoring the contributions of workers.',
  },
  {
    id: 4,
    name: 'Thanksgiving Day',
    img: '/images/labourDay.png',
    date: '28/11/2024',
    description: 'Giving thanks for the blessings of the harvest.',
  },
  {
    id: 5,
    name: 'Christmas Day',
    img: '/images/labourDay.png',
    date: '25/12/2024',
    description: 'Celebration of the birth of Jesus Christ.',
  },
  {
    id: 6,
    name: 'Easter Sunday',
    img: '/images/labourDay.png',
    date: '21/04/2024',
    description: 'Celebration of the resurrection of Jesus Christ.',
  },
  {
    id: 7,
    name: "Valentine's Day",
    img: '/images/labourDay.png',
    date: '14/02/2024',
    description: 'Celebration of love and affection.',
  },
  {
    id: 8,
    name: 'Halloween',
    img: '/images/halloween.jpg',
    date: '31/10/2024',
    description: 'Celebration of spooky traditions.',
  },
  {
    id: 9,
    name: 'Diwali',
    img: '/images/labourDay.png',
    date: '24/10/2024',
    description: 'Festival of lights celebrated by Hindus.',
  },
  {
    id: 10,
    name: 'Hanukkah',
    img: '/images/labourDay.png',
    date: '23/12/2024',
    description: 'Jewish festival of lights.',
  },
  {
    id: 11,
    name: 'Chinese New Year',
    img: '/images/labourDay.png',
    date: '25/01/2024',
    description: 'Celebration of the Chinese lunar new year.',
  },
  {
    id: 12,
    name: 'Eid al-Fitr',
    img: '/images/labourDay.png',
    date: '24/05/2024',
    description: 'Islamic festival marking the end of Ramadan.',
  },
  {
    id: 13,
    name: 'Oktoberfest',
    img: '/images/labourDay.png',
    date: '21/09/2024',
    description: 'Bavarian beer festival in Germany.',
  },
  {
    id: 14,
    name: 'Bastille Day',
    img: '/images/labourDay.png',
    date: '14/07/2024',
    description: 'French National Day commemorating the revolution.',
  },
  {
    id: 15,
    name: 'Cinco de Mayo',
    img: '/images/labourDay.png',
    date: '05/05/2024',
    description: 'Celebration of Mexican heritage and pride.',
  },
  {
    id: 16,
    name: 'Republic Day',
    img: '/images/republicDay.avif',
    date: '26/01/2024',
    description: 'Celebration of Republic Day and pride.',
  },
];
export default holidays;
